load_from:
- grpc_server:
    host: 127.0.0.1
    port: 12503
    location_name: kortravelgeo_dagster.definitions
- grpc_server:
    host: 127.0.0.1
    port: 12603
    location_name: ktc.dagster.definitions
- grpc_server:
    host: 127.0.0.1
    port: 12703
    location_name: kortravelmap.dagster.definitions
- grpc_server:
    host: 127.0.0.1
    port: 12803
    location_name: pinvi.etl.definitions
- grpc_server:
    host: 127.0.0.1
    port: 14106
    location_name: kortravelweather_dagster.definitions
- grpc_server:
    host: 127.0.0.1
    port: 14005
    location_name: kor-travel-transport
